version: "3.2"
services:
  insight:
    build: datascience
    depends_on:
      - birth_db
    ports:
      - "8888:8888"
    volumes:
      - ".:/home/jovyan/work"
  birth_db:
    build: birth_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
